#ifndef UCPD_PRL_SM_H
#define UCPD_PRL_SM_H

#include <stdint.h>

/* Protocol layer state machines states*/

/* Protocol layer chunked Rx state machine states */
typedef enum : uint8_t
{
	PRL_RCH_STATE_NONE,
	PRL_RCH_STATE_WAIT_FOR_MESSAGE_FROM_PRL,
	PRL_RCH_STATE_REPORT_ERROR,
	PRL_RCH_STATE_PASS_UP_MESSAGE,
	PRL_RCH_STATE_PROCESSING_EXTENDED_MESSAGE,
	PRL_RCH_STATE_REQUESTING_CHUNK,
	PRL_RCH_STATE_WAITING_CHUNK
} UCPD_PRL_SM_CHUNKED_RX_State;

/* Protocol layer chunked Tx state machine states */
typedef enum : uint8_t
{
	PRL_TCH_STATE_NONE,
	PRL_TCH_STATE_WAIT_FOR_MESSAGE_REQUEST_FROM_PE,
	PRL_TCH_STATE_PASS_DOWN_MESSAGE,
	PRL_TCH_STATE_WAIT_FOR_TRANSMISSION_COMPLETE,
	PRL_TCH_STATE_MESSAGE_SENT,
	PRL_TCH_STATE_REPORT_ERROR,
	PRL_TCH_STATE_PREPARE_TO_SEND_CHUNKED_MESSAGE,
	PRL_TCH_STATE_CONSTRUCT_CHUNKED_MESSAGE,
	PRL_TCH_STATE_SENDING_CHUNKED_MESSAGE,
	PRL_TCH_STATE_WAIT_CHUNK_REQUEST,
	PRL_TCH_STATE_MESSAGE_RECEIVED
} UCPD_PRL_SM_CHUNKED_TX_State;

/* Protocol layer chunked message router */
typedef enum : uint8_t
{
	PRL_RTR_STATE_NONE,
	PRL_RTR_STATE_WAIT_FOR_MESSAGE_FROM_RRL,
	PRL_RTR_STATE_RX_CHUNKS,
	PRL_RTR_STATE_PING,
	PRL_RTR_STATE_TX_CHUNKS
} UCPD_PRL_SM_CHUNKED_ROUTER_State;

/* Protocol layer transmission state machine states */
typedef enum : uint8_t
{
	PRL_TX_STATE_NONE,
	PRL_TX_STATE_PHY_LAYER_RESET,
	PRL_TX_STATE_DISCARD_MESSAGE,
	PRL_TX_STATE_SNK_START_OF_AMS,
	PRL_TX_STATE_SNK_PENDING,
	PRL_TX_STATE_LAYER_RESET_FOR_TRANSMIT,
	PRL_TX_STATE_WAIT_FOR_MESSAGE_REQUEST,
	PRL_TX_STATE_CONSTRUCT_MESSAGE,
	PRL_TX_STATE_WAIT_FOR_PHY_RESPONSE,
	PRL_TX_STATE_MATCH_MESSAGE_ID,
	PRL_TX_STATE_CHECK_RETRY_COUNTER,
	PRL_TX_STATE_TRANSMISSION_ERROR,
	PRL_TX_STATE_MESSAGE_SENT
} UCPD_PRL_SM_TX_State;

/* Protocol layer reception state machine states */
typedef enum : uint8_t
{
	PRL_RX_STATE_NONE,
	PRL_RX_STATE_LAYER_RESET_FOR_RECEIVE,
	PRL_RX_STATE_WAIT_FOR_PHY_MESSAGE,
	PRL_RX_STATE_SEND_GOODCRC,
	PRL_RX_STATE_CHECK_MESSAGE_ID,
	PRL_RX_STATE_STORE_MESSAGE_ID
} UCPD_PRL_SM_RX_State;

/* Protocol layer hard reset state machine states */
typedef enum : uint8_t
{
	PRL_HR_STATE_NONE,
	PRL_HR_STATE_RESET_LAYER,
	PRL_HR_STATE_REQUEST_HARD_RESET,
	PRL_HR_STATE_INDICATE_HARD_RESET,
	PRL_HR_STATE_WAIT_FOR_PHY_HARD_RESET_COMPLETE,
	PRL_HR_STATE_PHY_HARD_RESET_REQUESTED,
	PRL_HR_STATE_WAIT_FOR_PE_HARD_RESET_COMPLETE,
	PRL_HR_STATE_PE_HARD_RESET_COMPLETE
} UCPD_PRL_SM_HR_State;

#endif // UCPD_PRL_SM_H
